---
- name: Setup azuracast
  hosts: all
  gather_facts: no

  tasks:
    - name: Create a directory /var/azuracast
      ansible.builtin.file:
        path: /var/azuracast
        state: directory
        mode: '0755'
        
    - name: Install podman
      ansible.builtin.apt:
        name: podman
        state: present
        update_cache: yes
        
    - name: Install podman-compose
      ansible.builtin.apt:
        name: podman-compose
        state: present 
        
    - name: Download https://raw.githubusercontent.com/AzuraCast/AzuraCast/main/docker.sh
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/AzuraCast/AzuraCast/main/docker.sh
        dest: /var/azuracast/docker.sh
        mode: '0445'

    - name: Execute /var/azuracast/docker.sh install
      ansible.builtin.shell: printf 'N\nen_US\nno\nno\n' | /var/azuracast/docker.sh install
