name: 'Ansible'

on:
  workflow_run:
    workflows: ["Terraform"]
    types:
      - completed

jobs:
  ansible:
    name: 'Ansible'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
  
